name: Re-run on Failure

on:
  workflow_run:
    workflows: ["main"]     # Name of your main workflow
    types:
      - completed

jobs:
  rerun:
    # Checks if the run has failed
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Re-run the workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"master"}'
